name: clock_morse
description: Clock Morse Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  wear: 1.1.0
  flame_splash_screen: 0.1.0
  flame: 1.6.0

flutter_icons:
  android: true
  ios: true
  # image_path: "assets/logo.jpg"
  min_sdk_android: 23 # android min sdk min:16, default 21
  web:
    generate: true
  windows:
    generate: false
  macos:
    generate: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

#  assets:
#    - assets/image.gif

